---
- name: add php71 repo
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: install php71
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - build-essential
    - php7.1
    - php7.1-cli
    - php7.1-curl
    - php7.1-fpm
    - php7.1-intl
    - php7.1-json
    - php7.1-mcrypt
    - php7.1-mbstring
    - php7.1-gd
    - php7.1-dom
    - php7.1-opcache
    - php7.1-intl
    - php7.1-zip
    - php7.1-mysql
    - php7.1-soap

- name: copy php.ini
  template:
    src: php.ini
    dest: /etc/php/7.1/fpm/php.ini
  notify:
     - restart php-fpm
     
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
   creates: /usr/local/bin/composer
